# Generated by Django 6.0.5 on 2026-06-15 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_bien_cliente'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(help_text='Nombre de la calle', max_length=150)),
                ('numero_exterior', models.CharField(help_text='Número exterior de la dirección', max_length=20)),
                ('numero_interior', models.CharField(blank=True, default='', help_text='Número interior (opcional)', max_length=20)),
                ('ciudad', models.CharField(help_text='Ciudad', max_length=100)),
                ('codigo_postal', models.CharField(help_text='Código postal', max_length=10)),
                ('estado', models.CharField(help_text='Estado o provincia', max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud de la dirección', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud de la dirección', max_digits=9)),
                ('notas_adicionales', models.TextField(blank=True, default='', help_text='Notas adicionales de la dirección', max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AlterModelOptions(
            name='bien',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Bien', 'verbose_name_plural': 'Bienes'},
        ),
        migrations.AlterField(
            model_name='bien',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='descripcion',
            field=models.CharField(help_text='Descripción detallada del bien', max_length=500),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estatus',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('En tránsito', 'En tránsito'), ('Entregado', 'Entregado')], default='Registrado', help_text='Estado actual del bien', max_length=50),
        ),
        migrations.AlterField(
            model_name='bien',
            name='identificador',
            field=models.CharField(help_text='Identificador único del bien (b-XXXX-YYYY)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Marca o fabricante del bien', max_length=100),
        ),
        migrations.AlterField(
            model_name='bien',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor del bien en pesos', max_digits=12),
        ),
        migrations.CreateModel(
            name='CamionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_camion', models.CharField(help_text='Identificador único del camión', max_length=20)),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud del camión', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud del camión', max_digits=9)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la actualización GPS')),
                ('validado', models.BooleanField(default=False, help_text='Indica si las coordenadas fueron validadas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
            ],
            options={
                'verbose_name': 'Registro GPS',
                'verbose_name_plural': 'Registros GPS',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['identificador_camion', 'fecha_hora'], name='bienes_cami_identif_5eef72_idx'), models.Index(fields=['fecha_hora'], name='bienes_cami_fecha_h_f7f9cd_idx')],
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, help_text='Dirección de entrega del bien', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes_entrega', to='bienes.direccion'),
        ),
        migrations.AddField(
            model_name='bien',
            name='direccion_recoleccion',
            field=models.ForeignKey(blank=True, help_text='Dirección de recolección del bien', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bienes_recoleccion', to='bienes.direccion'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['cliente', 'estatus'], name='bienes_bien_cliente_f641d9_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['-creado_en'], name='bienes_bien_creado__2fb679_idx'),
        ),
    ]
