# Generated by Django 6.0.5 on 2026-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion_id', models.CharField(max_length=30)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registrado_en', models.DateTimeField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
