# Generated by Django 6.0.5 on 2026-06-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='anonimo', help_text='Rol del usuario que realizó la acción', max_length=50)),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('login_fallido', 'Intento fallido de inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear_bien', 'Crear bien'), ('actualizar_bien', 'Actualizar bien'), ('eliminar_bien', 'Eliminar bien'), ('crear_direccion', 'Crear dirección'), ('actualizar_direccion', 'Actualizar dirección'), ('consultar_reporte', 'Consultar reporte'), ('consultar_bitacora', 'Consultar bitácora'), ('actualizar_gps', 'Actualización GPS'), ('acceso_no_autorizado', 'Intento de acceso no autorizado')], help_text='Tipo de acción realizada', max_length=50)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='exitoso', help_text='Resultado de la acción', max_length=20)),
                ('descripcion', models.TextField(help_text='Detalles adicionales de la acción')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Dirección IP del origen de la solicitud', null=True)),
                ('metodo_http', models.CharField(default='GET', help_text='Método HTTP utilizado', max_length=10)),
                ('ruta', models.CharField(help_text='Ruta o endpoint accedido', max_length=500)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON para auditoría')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la acción')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='seguridad_b_fecha_h_f29baa_idx'), models.Index(fields=['usuario', 'fecha_hora'], name='seguridad_b_usuario_63618d_idx'), models.Index(fields=['accion'], name='seguridad_b_accion_49b1ac_idx')],
            },
        ),
    ]
